<?XML VERSION="1.0"?>


<!--
	Bayesian network in BIF (BayesNet Interchange Format)
	Produced by JavaBayes (http://www.cs.cmu.edu/~javabayes/
	Output created Fri Nov 14 13:14:15 GMT+00:00 1997
-->



<!-- DTD for the BIF format -->
<!DOCTYPE BIF [
	<!ELEMENT PROPERTY (#PCDATA)>
	<!ELEMENT TYPE (#PCDATA)>
	<!ELEMENT VALUE (#PCDATA)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT NETWORK
		( NAME, ( PROPERTY | VARIABLE | PROBABILITY )* )>
	<!ELEMENT VARIABLE ( NAME, TYPE, ( VALUE |  PROPERTY )* ) >
	<!ELEMENT PROBABILITY
		( FOR | GIVEN | TABLE | ENTRY | DEFAULT | PROPERTY )* >
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT DEFAULT (TABLE)>
	<!ELEMENT ENTRY ( VALUE* , TABLE )>
]>


<BIF>
<NETWORK>
<NAME>John-Mary-Call</NAME>

<!-- Variables -->
<VARIABLE>
	<NAME>Burglary</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>False</VALUE>
	<VALUE>True</VALUE>
	<PROPERTY>position = (145, 114)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Earthquake</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>False</VALUE>
	<VALUE>True</VALUE>
	<PROPERTY>position = (351, 110)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Alarm</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>False</VALUE>
	<VALUE>True</VALUE>
	<PROPERTY>position = (253, 224)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>JohnCalls</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>False</VALUE>
	<VALUE>True</VALUE>
	<PROPERTY>position = (156, 343)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MaryCalls</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>False</VALUE>
	<VALUE>True</VALUE>
	<PROPERTY>position = (344, 341)</PROPERTY>
</VARIABLE>


<!-- Probability distributions -->
<PROBABILITY>
	<FOR>Burglary</FOR>
	<TABLE>0.999 0.0010 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Earthquake</FOR>
	<TABLE>0.998 0.0020 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Alarm</FOR>
	<GIVEN>Burglary</GIVEN>
	<GIVEN>Earthquake</GIVEN>
	<TABLE>0.999 0.71 0.06 0.05 0.0010 0.29 0.94 0.95 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>JohnCalls</FOR>
	<GIVEN>Alarm</GIVEN>
	<TABLE>0.95 0.1 0.05 0.9 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MaryCalls</FOR>
	<GIVEN>Alarm</GIVEN>
	<TABLE>0.99 0.3 0.01 0.7 </TABLE>
</PROBABILITY>


</BIF>
